//! Generates the embedded-stdlib table consumed by `src/stdlib.rs`.
//!
//! An installed `qn` must run outside a repo checkout, so the *shipping* subset of
//! `qnlib/` is compiled into the binary: the prelude, the test framework, and the
//! `core/` `net/` `web/` trees. Everything else in `qnlib/` (the language's own test
//! suite, benchmarks, stress corpora, presentation) is a source-tree feature and
//! stays on disk — see `docs/internal/RELEASE_PREP.md`.
//!
//! The table is generated rather than pulled in with `include_dir!` for two reasons:
//! it needs no dependency, and it lets us emit an exact `rerun-if-changed` per file
//! so editing a `.qn` rebuilds the binary (the embedded copy would otherwise go
//! stale). Development normally reads the stdlib from disk anyway — see the
//! `QUOIN_STDLIB` env var, set for cargo builds in `.cargo/config.toml`.

use std::path::{Path, PathBuf};

/// Directories under `qnlib/` whose `.qn` units ship in the binary.
const EMBEDDED_DIRS: &[&str] = &["core", "net", "web"];
/// Individual `qnlib/*.qn` units that ship in the binary.
const EMBEDDED_FILES: &[&str] = &["prelude", "test"];

fn main() {
    let qnlib = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("qnlib");
    println!("cargo:rerun-if-changed=build.rs");

    // (unit path without extension, absolute source path)
    let mut units: Vec<(String, PathBuf)> = Vec::new();

    for stem in EMBEDDED_FILES {
        units.push((stem.to_string(), qnlib.join(format!("{stem}.qn"))));
    }

    for dir in EMBEDDED_DIRS {
        let path = qnlib.join(dir);
        // A new/removed file in the directory changes the table itself.
        println!("cargo:rerun-if-changed={}", path.display());
        let entries = std::fs::read_dir(&path)
            .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
        for entry in entries {
            let file = entry.expect("dir entry").path();
            if file.extension().and_then(|e| e.to_str()) != Some("qn") {
                continue;
            }
            let stem = file
                .file_stem()
                .and_then(|s| s.to_str())
                .expect("utf-8 file stem");
            units.push((format!("{dir}/{stem}"), file));
        }
    }

    // UTF-8 lexicographic, matching `FsResolver::list`'s deterministic load order —
    // the `00-`..`11-` prefixes make lexicographic == numeric.
    units.sort_by(|a, b| a.0.cmp(&b.0));

    let mut out = String::from(
        "// @generated by build.rs — do not edit.\n\
         /// Every embedded stdlib unit as `(unit path without extension, source)`,\n\
         /// UTF-8-lexicographically sorted.\n\
         pub static UNITS: &[(&str, &str)] = &[\n",
    );
    for (unit, path) in &units {
        println!("cargo:rerun-if-changed={}", path.display());
        assert!(path.is_file(), "missing embedded unit {}", path.display());
        out.push_str(&format!(
            "    ({:?}, include_str!({:?})),\n",
            unit,
            path.display().to_string()
        ));
    }
    out.push_str("];\n");

    let dest = Path::new(&std::env::var("OUT_DIR").expect("OUT_DIR")).join("stdlib_table.rs");
    std::fs::write(&dest, out).expect("write stdlib table");
}
