# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quoin_ext_proto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ArrowDType(object):
    Float64 = 0
    Int64 = 1


class Message(object):
    NONE = 0
    Call = 1
    CallReturn = 2
    CallReturnResource = 3
    CallReturnArray = 4
    MakeString = 5
    HandleToString = 6
    Retain = 7
    Release = 8
    CallMethodOnHandle = 9
    InvokeBlock = 10
    InvokeBlockReturn = 11
    HostOpReturn = 12


class ArrowArray(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ArrowArray()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsArrowArray(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ArrowArray
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ArrowArray
    def Dtype(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ArrowArray
    def Length(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ArrowArray
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # ArrowArray
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # ArrowArray
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ArrowArray
    def DataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def ArrowArrayStart(builder):
    builder.StartObject(3)

def ArrowArrayAddDtype(builder, dtype):
    builder.PrependUint8Slot(0, dtype, 0)

def ArrowArrayAddLength(builder, length):
    builder.PrependUint64Slot(1, length, 0)

def ArrowArrayAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def ArrowArrayStartDataVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def ArrowArrayEnd(builder):
    return builder.EndObject()



class Call(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Call()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCall(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Call
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Call
    def Op(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Call
    def Arg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Call
    def Handles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # Call
    def HandlesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint64Flags, o)
        return 0

    # Call
    def HandlesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Call
    def HandlesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Call
    def Resources(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # Call
    def ResourcesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint64Flags, o)
        return 0

    # Call
    def ResourcesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Call
    def ResourcesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Call
    def Releases(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # Call
    def ReleasesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint64Flags, o)
        return 0

    # Call
    def ReleasesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Call
    def ReleasesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # Call
    def Arrays(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = ArrowArray()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Call
    def ArraysLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Call
    def ArraysIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

def CallStart(builder):
    builder.StartObject(6)

def CallAddOp(builder, op):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(op), 0)

def CallAddArg(builder, arg):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(arg), 0)

def CallAddHandles(builder, handles):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(handles), 0)

def CallStartHandlesVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def CallAddResources(builder, resources):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(resources), 0)

def CallStartResourcesVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def CallAddReleases(builder, releases):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(releases), 0)

def CallStartReleasesVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def CallAddArrays(builder, arrays):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(arrays), 0)

def CallStartArraysVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def CallEnd(builder):
    return builder.EndObject()



class HandleList(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HandleList()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHandleList(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HandleList
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HandleList
    def Handles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # HandleList
    def HandlesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint64Flags, o)
        return 0

    # HandleList
    def HandlesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # HandleList
    def HandlesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def HandleListStart(builder):
    builder.StartObject(1)

def HandleListAddHandles(builder, handles):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(handles), 0)

def HandleListStartHandlesVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def HandleListEnd(builder):
    return builder.EndObject()



class CallReturn(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CallReturn()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCallReturn(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CallReturn
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CallReturn
    def Result(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def CallReturnStart(builder):
    builder.StartObject(1)

def CallReturnAddResult(builder, result):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(result), 0)

def CallReturnEnd(builder):
    return builder.EndObject()



class CallReturnResource(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CallReturnResource()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCallReturnResource(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CallReturnResource
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CallReturnResource
    def Resource(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def CallReturnResourceStart(builder):
    builder.StartObject(1)

def CallReturnResourceAddResource(builder, resource):
    builder.PrependUint64Slot(0, resource, 0)

def CallReturnResourceEnd(builder):
    return builder.EndObject()



class CallReturnArray(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CallReturnArray()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCallReturnArray(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CallReturnArray
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CallReturnArray
    def Array(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = ArrowArray()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def CallReturnArrayStart(builder):
    builder.StartObject(1)

def CallReturnArrayAddArray(builder, array):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(array), 0)

def CallReturnArrayEnd(builder):
    return builder.EndObject()



class MakeString(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MakeString()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMakeString(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MakeString
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MakeString
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def MakeStringStart(builder):
    builder.StartObject(1)

def MakeStringAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def MakeStringEnd(builder):
    return builder.EndObject()



class HandleToString(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HandleToString()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHandleToString(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HandleToString
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HandleToString
    def Handle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def HandleToStringStart(builder):
    builder.StartObject(1)

def HandleToStringAddHandle(builder, handle):
    builder.PrependUint64Slot(0, handle, 0)

def HandleToStringEnd(builder):
    return builder.EndObject()



class Retain(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Retain()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRetain(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Retain
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Retain
    def Handle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def RetainStart(builder):
    builder.StartObject(1)

def RetainAddHandle(builder, handle):
    builder.PrependUint64Slot(0, handle, 0)

def RetainEnd(builder):
    return builder.EndObject()



class Release(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Release()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRelease(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Release
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Release
    def Handles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # Release
    def HandlesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint64Flags, o)
        return 0

    # Release
    def HandlesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Release
    def HandlesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ReleaseStart(builder):
    builder.StartObject(1)

def ReleaseAddHandles(builder, handles):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(handles), 0)

def ReleaseStartHandlesVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def ReleaseEnd(builder):
    return builder.EndObject()



class CallMethodOnHandle(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CallMethodOnHandle()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCallMethodOnHandle(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CallMethodOnHandle
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CallMethodOnHandle
    def Receiver(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # CallMethodOnHandle
    def Selector(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CallMethodOnHandle
    def Args(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # CallMethodOnHandle
    def ArgsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint64Flags, o)
        return 0

    # CallMethodOnHandle
    def ArgsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CallMethodOnHandle
    def ArgsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def CallMethodOnHandleStart(builder):
    builder.StartObject(3)

def CallMethodOnHandleAddReceiver(builder, receiver):
    builder.PrependUint64Slot(0, receiver, 0)

def CallMethodOnHandleAddSelector(builder, selector):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(selector), 0)

def CallMethodOnHandleAddArgs(builder, args):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(args), 0)

def CallMethodOnHandleStartArgsVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def CallMethodOnHandleEnd(builder):
    return builder.EndObject()



class InvokeBlock(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InvokeBlock()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInvokeBlock(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # InvokeBlock
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InvokeBlock
    def Block(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # InvokeBlock
    def Batches(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = HandleList()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # InvokeBlock
    def BatchesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # InvokeBlock
    def BatchesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def InvokeBlockStart(builder):
    builder.StartObject(2)

def InvokeBlockAddBlock(builder, block):
    builder.PrependUint64Slot(0, block, 0)

def InvokeBlockAddBatches(builder, batches):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(batches), 0)

def InvokeBlockStartBatchesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def InvokeBlockEnd(builder):
    return builder.EndObject()



class InvokeBlockReturn(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InvokeBlockReturn()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInvokeBlockReturn(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # InvokeBlockReturn
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InvokeBlockReturn
    def Results(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # InvokeBlockReturn
    def ResultsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint64Flags, o)
        return 0

    # InvokeBlockReturn
    def ResultsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # InvokeBlockReturn
    def ResultsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # InvokeBlockReturn
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def InvokeBlockReturnStart(builder):
    builder.StartObject(2)

def InvokeBlockReturnAddResults(builder, results):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(results), 0)

def InvokeBlockReturnStartResultsVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def InvokeBlockReturnAddError(builder, error):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)

def InvokeBlockReturnEnd(builder):
    return builder.EndObject()



class HostOpReturn(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HostOpReturn()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHostOpReturn(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HostOpReturn
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HostOpReturn
    def Handle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # HostOpReturn
    def Str(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # HostOpReturn
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def HostOpReturnStart(builder):
    builder.StartObject(3)

def HostOpReturnAddHandle(builder, handle):
    builder.PrependUint64Slot(0, handle, 0)

def HostOpReturnAddStr(builder, str):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(str), 0)

def HostOpReturnAddError(builder, error):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)

def HostOpReturnEnd(builder):
    return builder.EndObject()



class Envelope(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Envelope()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEnvelope(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Envelope
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Envelope
    def MsgType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Envelope
    def Msg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def EnvelopeStart(builder):
    builder.StartObject(2)

def EnvelopeAddMsgType(builder, msgType):
    builder.PrependUint8Slot(0, msgType, 0)

def EnvelopeAddMsg(builder, msg):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(msg), 0)

def EnvelopeEnd(builder):
    return builder.EndObject()



