# automatically generated by the FlatBuffers compiler, do not modify

# namespace: quoin_ext_proto

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class ArrowDType(object):
    Float64 = 0
    Int64 = 1


class DataValueKind(object):
    NONE = 0
    DvNull = 1
    DvBool = 2
    DvInt = 3
    DvBigInt = 4
    DvFloat = 5
    DvDecimal = 6
    DvStr = 7
    DvBytes = 8
    DvList = 9
    DvMap = 10


class Message(object):
    NONE = 0
    Call = 1
    CallReturn = 2
    CallReturnResource = 3
    CallReturnArray = 4
    CallReturnData = 5
    CallReturnHandle = 6
    MakeString = 7
    HandleToString = 8
    Retain = 9
    Release = 10
    CallMethodOnHandle = 11
    InvokeBlock = 12
    InvokeBlockReturn = 13
    GetGlobal = 14
    MakeValue = 15
    ReadHandle = 16
    ReadHandleReturn = 17
    HostOpReturn = 18


class ArrowArray(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ArrowArray()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsArrowArray(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ArrowArray
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ArrowArray
    def Dtype(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # ArrowArray
    def Length(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # ArrowArray
    def Data(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # ArrowArray
    def DataAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # ArrowArray
    def DataLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # ArrowArray
    def DataIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def ArrowArrayStart(builder):
    builder.StartObject(3)

def ArrowArrayAddDtype(builder, dtype):
    builder.PrependUint8Slot(0, dtype, 0)

def ArrowArrayAddLength(builder, length):
    builder.PrependUint64Slot(1, length, 0)

def ArrowArrayAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def ArrowArrayStartDataVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def ArrowArrayEnd(builder):
    return builder.EndObject()



class DvNull(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DvNull()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDvNull(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DvNull
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

def DvNullStart(builder):
    builder.StartObject(0)

def DvNullEnd(builder):
    return builder.EndObject()



class DvBool(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DvBool()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDvBool(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DvBool
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DvBool
    def V(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return bool(self._tab.Get(flatbuffers.number_types.BoolFlags, o + self._tab.Pos))
        return False

def DvBoolStart(builder):
    builder.StartObject(1)

def DvBoolAddV(builder, v):
    builder.PrependBoolSlot(0, v, 0)

def DvBoolEnd(builder):
    return builder.EndObject()



class DvInt(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DvInt()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDvInt(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DvInt
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DvInt
    def V(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def DvIntStart(builder):
    builder.StartObject(1)

def DvIntAddV(builder, v):
    builder.PrependInt64Slot(0, v, 0)

def DvIntEnd(builder):
    return builder.EndObject()



class DvBigInt(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DvBigInt()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDvBigInt(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DvBigInt
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DvBigInt
    def V(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def DvBigIntStart(builder):
    builder.StartObject(1)

def DvBigIntAddV(builder, v):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(v), 0)

def DvBigIntEnd(builder):
    return builder.EndObject()



class DvFloat(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DvFloat()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDvFloat(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DvFloat
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DvFloat
    def V(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float64Flags, o + self._tab.Pos)
        return 0.0

def DvFloatStart(builder):
    builder.StartObject(1)

def DvFloatAddV(builder, v):
    builder.PrependFloat64Slot(0, v, 0.0)

def DvFloatEnd(builder):
    return builder.EndObject()



class DvDecimal(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DvDecimal()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDvDecimal(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DvDecimal
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DvDecimal
    def V(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def DvDecimalStart(builder):
    builder.StartObject(1)

def DvDecimalAddV(builder, v):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(v), 0)

def DvDecimalEnd(builder):
    return builder.EndObject()



class DvStr(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DvStr()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDvStr(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DvStr
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DvStr
    def V(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def DvStrStart(builder):
    builder.StartObject(1)

def DvStrAddV(builder, v):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(v), 0)

def DvStrEnd(builder):
    return builder.EndObject()



class DvBytes(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DvBytes()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDvBytes(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DvBytes
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DvBytes
    def V(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # DvBytes
    def VAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint8Flags, o)
        return 0

    # DvBytes
    def VLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DvBytes
    def VIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def DvBytesStart(builder):
    builder.StartObject(1)

def DvBytesAddV(builder, v):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(v), 0)

def DvBytesStartVVector(builder, numElems):
    return builder.StartVector(1, numElems, 1)

def DvBytesEnd(builder):
    return builder.EndObject()



class DvList(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DvList()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDvList(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DvList
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DvList
    def Items(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = DataValueBox()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DvList
    def ItemsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DvList
    def ItemsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def DvListStart(builder):
    builder.StartObject(1)

def DvListAddItems(builder, items):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(items), 0)

def DvListStartItemsVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def DvListEnd(builder):
    return builder.EndObject()



class DvEntry(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DvEntry()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDvEntry(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DvEntry
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DvEntry
    def Key(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # DvEntry
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = DataValueBox()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def DvEntryStart(builder):
    builder.StartObject(2)

def DvEntryAddKey(builder, key):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(key), 0)

def DvEntryAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def DvEntryEnd(builder):
    return builder.EndObject()



class DvMap(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DvMap()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDvMap(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DvMap
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DvMap
    def Entries(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = DvEntry()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # DvMap
    def EntriesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # DvMap
    def EntriesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def DvMapStart(builder):
    builder.StartObject(1)

def DvMapAddEntries(builder, entries):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(entries), 0)

def DvMapStartEntriesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def DvMapEnd(builder):
    return builder.EndObject()



class DataValueBox(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = DataValueBox()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsDataValueBox(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # DataValueBox
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # DataValueBox
    def VType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # DataValueBox
    def V(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def DataValueBoxStart(builder):
    builder.StartObject(2)

def DataValueBoxAddVType(builder, vType):
    builder.PrependUint8Slot(0, vType, 0)

def DataValueBoxAddV(builder, v):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(v), 0)

def DataValueBoxEnd(builder):
    return builder.EndObject()



class Call(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Call()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCall(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Call
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Call
    def Op(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Call
    def Arg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # Call
    def Handles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # Call
    def HandlesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint64Flags, o)
        return 0

    # Call
    def HandlesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Call
    def HandlesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

    # Call
    def Resources(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # Call
    def ResourcesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint64Flags, o)
        return 0

    # Call
    def ResourcesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Call
    def ResourcesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        return o == 0

    # Call
    def Releases(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # Call
    def ReleasesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint64Flags, o)
        return 0

    # Call
    def ReleasesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Call
    def ReleasesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        return o == 0

    # Call
    def Arrays(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = ArrowArray()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Call
    def ArraysLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Call
    def ArraysIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        return o == 0

    # Call
    def Data(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(16))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = DataValueBox()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def CallStart(builder):
    builder.StartObject(7)

def CallAddOp(builder, op):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(op), 0)

def CallAddArg(builder, arg):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(arg), 0)

def CallAddHandles(builder, handles):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(handles), 0)

def CallStartHandlesVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def CallAddResources(builder, resources):
    builder.PrependUOffsetTRelativeSlot(3, flatbuffers.number_types.UOffsetTFlags.py_type(resources), 0)

def CallStartResourcesVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def CallAddReleases(builder, releases):
    builder.PrependUOffsetTRelativeSlot(4, flatbuffers.number_types.UOffsetTFlags.py_type(releases), 0)

def CallStartReleasesVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def CallAddArrays(builder, arrays):
    builder.PrependUOffsetTRelativeSlot(5, flatbuffers.number_types.UOffsetTFlags.py_type(arrays), 0)

def CallStartArraysVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def CallAddData(builder, data):
    builder.PrependUOffsetTRelativeSlot(6, flatbuffers.number_types.UOffsetTFlags.py_type(data), 0)

def CallEnd(builder):
    return builder.EndObject()



class HandleList(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HandleList()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHandleList(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HandleList
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HandleList
    def Handles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # HandleList
    def HandlesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint64Flags, o)
        return 0

    # HandleList
    def HandlesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # HandleList
    def HandlesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def HandleListStart(builder):
    builder.StartObject(1)

def HandleListAddHandles(builder, handles):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(handles), 0)

def HandleListStartHandlesVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def HandleListEnd(builder):
    return builder.EndObject()



class CallReturn(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CallReturn()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCallReturn(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CallReturn
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CallReturn
    def Result(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def CallReturnStart(builder):
    builder.StartObject(1)

def CallReturnAddResult(builder, result):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(result), 0)

def CallReturnEnd(builder):
    return builder.EndObject()



class CallReturnResource(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CallReturnResource()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCallReturnResource(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CallReturnResource
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CallReturnResource
    def Resource(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def CallReturnResourceStart(builder):
    builder.StartObject(1)

def CallReturnResourceAddResource(builder, resource):
    builder.PrependUint64Slot(0, resource, 0)

def CallReturnResourceEnd(builder):
    return builder.EndObject()



class CallReturnArray(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CallReturnArray()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCallReturnArray(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CallReturnArray
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CallReturnArray
    def Array(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = ArrowArray()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def CallReturnArrayStart(builder):
    builder.StartObject(1)

def CallReturnArrayAddArray(builder, array):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(array), 0)

def CallReturnArrayEnd(builder):
    return builder.EndObject()



class CallReturnData(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CallReturnData()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCallReturnData(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CallReturnData
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CallReturnData
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = DataValueBox()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def CallReturnDataStart(builder):
    builder.StartObject(1)

def CallReturnDataAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def CallReturnDataEnd(builder):
    return builder.EndObject()



class MakeString(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MakeString()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMakeString(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MakeString
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MakeString
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def MakeStringStart(builder):
    builder.StartObject(1)

def MakeStringAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def MakeStringEnd(builder):
    return builder.EndObject()



class HandleToString(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HandleToString()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHandleToString(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HandleToString
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HandleToString
    def Handle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def HandleToStringStart(builder):
    builder.StartObject(1)

def HandleToStringAddHandle(builder, handle):
    builder.PrependUint64Slot(0, handle, 0)

def HandleToStringEnd(builder):
    return builder.EndObject()



class Retain(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Retain()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRetain(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Retain
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Retain
    def Handle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def RetainStart(builder):
    builder.StartObject(1)

def RetainAddHandle(builder, handle):
    builder.PrependUint64Slot(0, handle, 0)

def RetainEnd(builder):
    return builder.EndObject()



class Release(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Release()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsRelease(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Release
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Release
    def Handles(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # Release
    def HandlesAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint64Flags, o)
        return 0

    # Release
    def HandlesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # Release
    def HandlesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

def ReleaseStart(builder):
    builder.StartObject(1)

def ReleaseAddHandles(builder, handles):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(handles), 0)

def ReleaseStartHandlesVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def ReleaseEnd(builder):
    return builder.EndObject()



class CallMethodOnHandle(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CallMethodOnHandle()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCallMethodOnHandle(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CallMethodOnHandle
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CallMethodOnHandle
    def Receiver(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # CallMethodOnHandle
    def Selector(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # CallMethodOnHandle
    def Args(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # CallMethodOnHandle
    def ArgsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint64Flags, o)
        return 0

    # CallMethodOnHandle
    def ArgsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # CallMethodOnHandle
    def ArgsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        return o == 0

def CallMethodOnHandleStart(builder):
    builder.StartObject(3)

def CallMethodOnHandleAddReceiver(builder, receiver):
    builder.PrependUint64Slot(0, receiver, 0)

def CallMethodOnHandleAddSelector(builder, selector):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(selector), 0)

def CallMethodOnHandleAddArgs(builder, args):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(args), 0)

def CallMethodOnHandleStartArgsVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def CallMethodOnHandleEnd(builder):
    return builder.EndObject()



class InvokeBlock(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InvokeBlock()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInvokeBlock(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # InvokeBlock
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InvokeBlock
    def Block(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # InvokeBlock
    def Batches(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Vector(o)
            x += flatbuffers.number_types.UOffsetTFlags.py_type(j) * 4
            x = self._tab.Indirect(x)
            obj = HandleList()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # InvokeBlock
    def BatchesLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # InvokeBlock
    def BatchesIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        return o == 0

def InvokeBlockStart(builder):
    builder.StartObject(2)

def InvokeBlockAddBlock(builder, block):
    builder.PrependUint64Slot(0, block, 0)

def InvokeBlockAddBatches(builder, batches):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(batches), 0)

def InvokeBlockStartBatchesVector(builder, numElems):
    return builder.StartVector(4, numElems, 4)

def InvokeBlockEnd(builder):
    return builder.EndObject()



class InvokeBlockReturn(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = InvokeBlockReturn()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsInvokeBlockReturn(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # InvokeBlockReturn
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # InvokeBlockReturn
    def Results(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 8))
        return 0

    # InvokeBlockReturn
    def ResultsAsNumpy(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.GetVectorAsNumpy(flatbuffers.number_types.Uint64Flags, o)
        return 0

    # InvokeBlockReturn
    def ResultsLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

    # InvokeBlockReturn
    def ResultsIsNone(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        return o == 0

    # InvokeBlockReturn
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def InvokeBlockReturnStart(builder):
    builder.StartObject(2)

def InvokeBlockReturnAddResults(builder, results):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(results), 0)

def InvokeBlockReturnStartResultsVector(builder, numElems):
    return builder.StartVector(8, numElems, 8)

def InvokeBlockReturnAddError(builder, error):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)

def InvokeBlockReturnEnd(builder):
    return builder.EndObject()



class HostOpReturn(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = HostOpReturn()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsHostOpReturn(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # HostOpReturn
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # HostOpReturn
    def Handle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # HostOpReturn
    def Str(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

    # HostOpReturn
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def HostOpReturnStart(builder):
    builder.StartObject(3)

def HostOpReturnAddHandle(builder, handle):
    builder.PrependUint64Slot(0, handle, 0)

def HostOpReturnAddStr(builder, str):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(str), 0)

def HostOpReturnAddError(builder, error):
    builder.PrependUOffsetTRelativeSlot(2, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)

def HostOpReturnEnd(builder):
    return builder.EndObject()



class GetGlobal(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = GetGlobal()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsGetGlobal(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # GetGlobal
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # GetGlobal
    def Name(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def GetGlobalStart(builder):
    builder.StartObject(1)

def GetGlobalAddName(builder, name):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(name), 0)

def GetGlobalEnd(builder):
    return builder.EndObject()



class MakeValue(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = MakeValue()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsMakeValue(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # MakeValue
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # MakeValue
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = DataValueBox()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

def MakeValueStart(builder):
    builder.StartObject(1)

def MakeValueAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def MakeValueEnd(builder):
    return builder.EndObject()



class ReadHandle(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReadHandle()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReadHandle(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReadHandle
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReadHandle
    def Handle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def ReadHandleStart(builder):
    builder.StartObject(1)

def ReadHandleAddHandle(builder, handle):
    builder.PrependUint64Slot(0, handle, 0)

def ReadHandleEnd(builder):
    return builder.EndObject()



class ReadHandleReturn(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = ReadHandleReturn()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsReadHandleReturn(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # ReadHandleReturn
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # ReadHandleReturn
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            obj = DataValueBox()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # ReadHandleReturn
    def Error(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.String(o + self._tab.Pos)
        return None

def ReadHandleReturnStart(builder):
    builder.StartObject(2)

def ReadHandleReturnAddValue(builder, value):
    builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)

def ReadHandleReturnAddError(builder, error):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(error), 0)

def ReadHandleReturnEnd(builder):
    return builder.EndObject()



class CallReturnHandle(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = CallReturnHandle()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsCallReturnHandle(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # CallReturnHandle
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # CallReturnHandle
    def Handle(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def CallReturnHandleStart(builder):
    builder.StartObject(1)

def CallReturnHandleAddHandle(builder, handle):
    builder.PrependUint64Slot(0, handle, 0)

def CallReturnHandleEnd(builder):
    return builder.EndObject()



class Envelope(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Envelope()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsEnvelope(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Envelope
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Envelope
    def MsgType(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

    # Envelope
    def Msg(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            from flatbuffers.table import Table
            obj = Table(bytearray(), 0)
            self._tab.Union(obj, o)
            return obj
        return None

def EnvelopeStart(builder):
    builder.StartObject(2)

def EnvelopeAddMsgType(builder, msgType):
    builder.PrependUint8Slot(0, msgType, 0)

def EnvelopeAddMsg(builder, msg):
    builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(msg), 0)

def EnvelopeEnd(builder):
    return builder.EndObject()



